source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem "bridgetown", "~> 0.21"
gem "nokogiri"

gem "bridgetown-quick-search", "~> 1.1", :group => :bridgetown_plugins
